name: hawacom_update
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10
  video_player: ^2.9.2
  equatable: ^2.0.5

  # Firebase Core (Required)
  firebase_core: ^2.24.2

  # Firebase Cloud Messaging (Push Notifications)
  firebase_messaging: ^14.7.9

  # Firebase Database (Chat real-time)
  firebase_database: ^10.4.0

  # Firebase Storage (File uploads)
  firebase_storage: ^11.5.6

  # Local Notifications
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/icons/
    - assets/images/
    - assets/videos/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700